services:
  app:
    build:
      args:
        user: dev
        uid: 1000
        devrun: true
      target: dev
    entrypoint: ""
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: millennium-format.test
      DB_HOST: db-millennium-format
      CLOUDFLARE_R2_ENDPOINT: http://localstack-millennium-format:4566
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ~/.ssh:/root/.ssh
  db:
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./docker-compose/postgres/data:/var/lib/postgresql/data
      - ./docker-compose/postgres/logs:/var/log/postgresql
      - ./docker-compose/postgres/sql:/docker-entrypoint-initdb.d
  nginx:
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - ./docker-compose/nginx/ssl:/etc/nginx/conf.d/ssl
  redis:
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./docker-compose/redis/data:/data
  localstack:
    image: localstack/localstack
    container_name: localstack-millennium-format
    ports:
      - "4566:4566"
    volumes:
      - ./docker-compose/localstack/init-s3.py:/etc/localstack/init/ready.d/init-s3.py
    networks:
      - millennium-format