services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: app
    entrypoint: ./entrypoint.sh
    container_name: app-project-lost
    depends_on:
      - db
      - redis
    networks:
      - project-lost
  db:
    image: postgres:17.5-alpine
    container_name: db-project-lost
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USERNAME}
      PGPASSWORD: ${DB_PASSWORD}
    networks:
      - project-lost
  nginx:
    image: nginx:1.28-alpine
    container_name: nginx-project-lost
    networks:
      - project-lost
  redis:
    image: redis:8.0-alpine
    container_name: redis-project-lost
    networks:
      - project-lost
networks:
  project-lost:
    driver: bridge