services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: app
    entrypoint: ./entrypoint.sh
    container_name: app-millennium-format
    depends_on:
      - db
      - redis
    networks:
      - millennium-format
  db:
    image: postgres:17.5-alpine
    container_name: db-millennium-format
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USERNAME}
      PGPASSWORD: ${DB_PASSWORD}
    networks:
      - millennium-format
  nginx:
    image: nginx:1.28-alpine
    container_name: nginx-millennium-format
    networks:
      - millennium-format
  redis:
    image: redis:8.0-alpine
    container_name: redis-millennium-format
    networks:
      - millennium-format
networks:
  millennium-format:
    driver: bridge