name: Docker Build

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
  pull_request:
    branches:
      - master
    paths:
      - 'Dockerfile'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build --target production .